apiVersion: v2
name: bitwardenrs
description: Unofficial Bitwarden compatible server written in Rust
type: application
version: 0.1.4
appVersion: 1.15.1
keywords:
  - bitwarden
  - bitwarden_rs
  - password
sources:
  - https://github.com/dani-garcia/bitwarden_rs
maintainers:
  - name: Silvio Gissi
    email: silvio@gissilabs.com
