apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-app'
  labels:
    katenary.io/component: app
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: app
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: app
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: app
          image: '{{ .Values.app.repository.image }}{{ if ne .Values.app.repository.tag "" }}:{{ .Values.app.repository.tag }}{{ end }}'
          ports:
            - name: app
              containerPort: 80
          env:
            - name: DB_PORT
              value: '{{ tpl .Values.app.environment.DB_PORT . }}'
            - name: DB_DATABASE
              value: '{{ tpl .Values.app.environment.DB_DATABASE . }}'
            - name: DB_USERNAME
              value: '{{ tpl .Values.app.environment.DB_USERNAME . }}'
            - name: DB_PASSWORD
              value: '{{ tpl .Values.app.environment.DB_PASSWORD . }}'
            - name: DB_CONNECTION
              value: '{{ tpl .Values.app.environment.DB_CONNECTION . }}'
            - name: DB_HOST
              value: '{{ tpl .Values.app.environment.DB_HOST . }}'

