app:
  environment:
    extraEnv: []
  repository:
    image: civilfleet/generic
    tag: main
persistence:
  ## Persistent Volume storage class
  # storageClass: "-"
  ## Use existing Persistent Volume Claim
  # existingClaim: